name: Codeclimate

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run tests with coverage
        run: npm run test -- --coverage
      - name: Upload coverage to Codeclimate
        uses: codeclimate/codeclimate-github-action@v1
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}

